### ISSUE TITLE
Tie random seed to PYTHONHASHSEED

### ISSUE THREAD

**Issue by adamchainz** [pytest-dev/pytest-randomly#11]
It would be cool if this plugin could use `PYTHONHASHSEED` for the source of randomness so that tests are even more predictable. Setting it is probably outside the scope of the plugin since from inside the python interpreter it requires a restart which isn't such a great thing (though `python-libfaketime` gets away with it), however some tools like `tox` set it.

**Comment by majuscule** [comment]
Was wondering if I could help here and wanted to clarify as I think I'm missing something. Would this be as simple as `default=os.environ.get('PYTHONHASHSEED', int(time.time()))` in `pytest_addoption`?

**Comment by adamchainz** [comment]
Maybe, the ideal solution would allow `--randomly-seed=123` to control `PYTHONHASHSEED` though.

**Comment by majuscule** [comment]
How about setting `PYTHONHASHSEED` and calling `os.execve`? Not sure how that would interact with any callers.

**Comment by adamchainz** [comment]
That's what `python-libfaketime` does :) I found it okay but it can break other stuff, I'm not sure how to proceed here, or if it's worth it as PYTHONHASHSEED doesn't change dictionary iteration order after Python 3.6.

**Comment by adamchainz** [comment]
Closing due to age. It's probably not worth supporting it due to Python 3.6 stopping changing dictionary iteration order.
