### ISSUE TITLE
mimesis support

### ISSUE THREAD

**Issue by sobolevn** [pytest-dev/pytest-randomly#135]
Hi, I am one of the developers of [`mimesis`](https://github.com/lk-geimfari/mimesis) and a huge fan of your library.

I really want to provide a native integration of `mimesis` and `pytest-randomly` just like the one you have with `faker` and `factoryboy`. I really like that the reseed happens before each test, so the results are significantly better than the regular one time seed.

What needs to be done? 
1. From our side we have changed how `random` is used internally to expose global `random` instance: https://github.com/lk-geimfari/mimesis/pull/471/files#diff-02fe14a63fc506efde39da2f898b5e0fR127 so it would be easy to seed it
2. I can provide a PR with the same logic as you already use for `faker` and others, if that's fine

Related: https://github.com/lk-geimfari/mimesis/issues/469
I would like to hear your opinion. Thanks!

**Comment by adamchainz** [comment]
Thanks, I hadn't heard of mimesis before but it looks useful. Sounds like you're ready to make the PR!

Add mimesis to requirements.in, recompile requirements.txt (on python 2.7), add the logic and a test, and a note in HISTORY.rst for the next release. Thanks!

**Comment by sobolevn** [comment]
Hm, `mimesis` support only `python3`.

I can see two ways of solving this:
1. we can just check if `mimesis` is installed as usual (it simply won't be installed on any `python2` env since it uses type hints)
2. we can also explicitly check if `mimesis` is installed and `python == 3`

The only question for me is how to properly add this dependency to `requirements.in`. I usually solve this problem with `pipenv` or `poetry`.

@adamchainz what do you recommend? Thanks!

**Comment by adamchainz** [comment]
Oh dear. I've been meaning to move to pipenv, just haven't got around to it. If you can figure out a setup for this project that would be very helpful as I could replicate it on my other projects.

As for implementation, your first version seems fine to me.

**Comment by adamchainz** [comment]
Hi @sobolevn 

I haven't moved to `pipenv` because I found it complicated to roll out against all my repos (specifically testing all the versions of django). But now `pytest-randomly` is Python 3 only, I think it can support `mimesis`? It seems that you are exposing your random generator as `mimesis.random.random`.

**Comment by sobolevn** [comment]
@adamchainz wow, I have completely forgot about this feature. Awesome to come back to it.

Yes, here's the exact line when the global `Random` instance is created: https://github.com/lk-geimfari/mimesis/blob/master/mimesis/random.py#L129

**Comment by adamchainz** [comment]
I don't have time to work on this, if you still want the mimesis support, please make a PR, thanks!

**Comment by lk-geimfari** [comment]
@adamchainz Hi! I want to work on this issue. Can you, please, tell me what steps exactly should I do?

**Comment by adamchainz** [comment]
@lk-geimfari I just merged and released #187 which adds a package entrypoint that can be used for reseeding. Adding such an entrypoint to mimesis would be the way to go now!
