### ISSUE TITLE
Switch to pipenv

### ISSUE THREAD

**Issue by sobolevn** [pytest-dev/pytest-randomly#136]
As we have discussed in https://github.com/pytest-dev/pytest-randomly/issues/135#issuecomment-398190536 there's an issue with optional dependencies.

Switching to `pipenv` will include:
1. Removing `requirements.in` and `requirements.txt`
2. Adding `Pipfile` and `Pipfile.lock`
3. Changing how `tox` works

That's it.
Later I will move to #135

**Comment by adamchainz** [comment]
👍 Thanks

**Comment by tuukkamustonen** [comment]
Perhaps close this, as the PR was closed, too, @adamchainz.

**Comment by adamchainz** [comment]
Aye, thanks.
