### ISSUE TITLE
Support `@seed` decorator

### ISSUE THREAD

**Issue by sobolevn** [pytest-dev/pytest-randomly#140]
## Problem

Sometimes I ran tests with some random values that pass.
When the seed changes during the next test run I might run into some errors.

Consider this imaginary example:

```python
import random

def will_fail(x):
    return x / random.randint(0, 10)

def test_will_fail():
    assert isinstance(will_fail(5), float)
```

The test will pass for some seeds, but later I will run into the situation when this test will fail.
So, I will fix the code, like this:

```python
def will_fail(x):
    return x / random.randint(1, 10)
```

And I want to be sure that this won't happen again.

## Current solution

I can manually run `random.seed` and set seed values from the previous failing tests.

## Proposed solution

I see this as a huge API feature, that will cover these cases.
It may look something like this:

```python
@pytest.mark.seed('your-seed')  # we had failures with this seed in the past!
@pytest.mark.seed('your-other-seed')  # this seed is also breaking our code
def test_will_fail():
    ... 
```

By doing this we can change the global random seed for a single test. We can do it multiple times. And then return back to normal tests execution.

This API is inspired by `hypothesis`: https://hypothesis.readthedocs.io/en/latest/reproducing.html?highlight=seed

**Comment by adamchainz** [comment]
What if there was a pytest fixture or context manager? Then we could have

```py
@pytest.mark.parametrize('seed', [9001, 1337])
def test_old_bad_seeds(seed, randomly):
    randomly.reseed(seed)
    # test that has failed in the past with those exact seeds
```

Tbh I'm not that excited about this though. I think if you find a failing test with a particular *seed*, it's not the *seed* that should be turned into a new test case but the actual underlying data that caused the failure. For example if seed 9001 caused your data generator to create a user with a really long name, add a test with a user with a fixed really long name.

Fixing the seed in a test run is pretty fragile, as the data generator could change in the future, meaning the seed values don't mean the same thing, so the tests could stop testing the specific bugs they exposed. For example, new versions of `faker` come with new data, remapping the data returned for a given seed.

Do you have a use case that prevents making tests with fixed test data, or at makes it impractical?

**Comment by sobolevn** [comment]
> Fixing the seed in a test run is pretty fragile, as the data generator could change in the future, meaning the seed values don't mean the same thing, so the tests could stop testing the specific bugs they exposed

Yeap, that seems reasonable. `hypothesis` spoiled me here.
I will stick to the data examples.

**Comment by adamchainz** [comment]
Btw `hypothesis` has `@example` for this - https://hypothesis.readthedocs.io/en/latest/reproducing.html#providing-explicit-examples . But that can't have an analog in `pytest-randomly` because we don't touch data generation :)
