### ISSUE TITLE
Different test order on different machines but --randomly-seed is the same?

### ISSUE THREAD

**Issue by danieljacobs1** [pytest-dev/pytest-randomly#151]
Hi,

I have a question about how the `--randomly-seed` option works.

Recently we had a test failure on our CI system, and since we use `pytest-randomly` I grabbed the seed value from the output on the CI job and ran the test on my machine.

What I noticed was that despite using the same `--randomly-seed` value, the tests ran in a different order on my machine. And in fact the tests all passed on my machine.

My question then is, is it expected that the test order be different on different machines for the same `--randomly-seed` value?

Thanks,

Dan

**Comment by adamchainz** [comment]
No the test order should be the same. What other differences are there between the environments? Are there a different number of tests being run on CI (e.g. there are some 'slow' tests using a mark to get run on CI only) or they using different Python versions (the only difference I'm aware of is between 2 and 3 though)?

**Comment by danieljacobs1** [comment]
The number of tests is the same on the CI system and locally, as is the Python version (3.6.2). The tests are fast (less than 1min 30 seconds) so we always run them all.

The CI system uses Docker containers to run the tests - could that have an impact?

**Comment by adamchainz** [comment]
Unlikely it's *just* the use of Docker containers. But you can run the same docker container locally and see if you get the same result? Also check for interactions with other pytest plugins and features, e.g. if you're using pytest-vw ( https://github.com/The-Compiler/pytest-vw ) that will definitely interfere 😂

**Comment by danieljacobs1** [comment]
Yes, I did run the tests in the Docker container locally and they ran in the same order as on CI for that seed.

Good point about pytest plugins. We use these ones (from pytest output):
```
plugins: randomly-1.2.3, instafail-0.4.0, cov-2.5.1, asyncio-0.8.0, aiohttp-0.3.0
```
both locally and on CI. Other version info is:
```
pytest-3.6.2, py-1.5.3, pluggy-0.6.0
```
We do have sync and async code in this repo, so need the async plugins to support testing that code.

We definitely don't use `pytest-vw` :grinning:

**Comment by adamchainz** [comment]
Try running a simple `random.seed()` then `random.random()` function in both environments and seeing if they turn out the same? Idk where else to look then.

**Comment by danieljacobs1** [comment]
Unfortunately I get consistent results, at least in the Python REPL:

```
>>> import random
>>> random.seed(1024)
>>> random.random()
0.7970515714521261
>>> random.seed(1539246755)
>>> random.random()
0.18822749704109154
```

I'll keep digging as and when I have time and post here what I find.

**Comment by adamchainz** [comment]
Closing due to age.
