### ISSUE TITLE
v2.1.0 dropped the test module from the sdist

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/pytest-randomly#172]
In the recent re-organisation of the tests, the new module isnt being included into the sdist.

**Comment by adamchainz** [comment]
Fixed and released in 2.1.1!

**Comment by jayvdb** [comment]
Thanks. Submitted as https://build.opensuse.org/request/show/688847 . Note if you actually break py2.7 before it is EOL, you are creating work for me as I'll need to figure out how to unbreak it. :P

**Comment by jayvdb** [comment]
On the flip side, I've noticed that openSUSE's maintainers are already letting packages break on Python 3.4.
