### ISSUE TITLE
Is it possible to get random seed value in test function?

### ISSUE THREAD

**Issue by zpan** [pytest-dev/pytest-randomly#192]
Many thanks for the awesome plugin, really help a lot.

I wonder is it possible to get random seed value during pytest running ?

e.g. 

```
def test_get_ramdom_seed():
    print(seed)
```

Thanks in advance!

**Comment by adamchainz** [comment]
You can find the current seed through the pytest config object, like the plugin does here: https://github.com/pytest-dev/pytest-randomly/blob/master/pytest_randomly.py#L91

I know there's some correct way to access the config object from within a test but can't remember it right now, it's probably in the docs. If you find a way would be great to have it documented here.

The other thing you can use is `random.getstate` which captures the exact state of the random generator, which depends on the seed then how many times it has been used. Useful if you want to reset to an exact state, as pytest randomly does.

**Comment by zpan** [comment]
Many thanks for your response.
Below works and helps me to resolve the problem. 
```
seed = config.getoption("randomly_seed") + offset
```
Will update here if i found other ways.

**Comment by adamchainz** [comment]
👍 Will look at documenting

I think within a test the config is best accessed through the `request` fixture, from which `request.config` can be fetched. (see https://pytest.readthedocs.io/en/latest/example/simple.html#pass-different-values-to-a-test-function-depending-on-command-line-options )

**Comment by adamchainz** [comment]
So as commented in #251, there probably isn't a use case for finding the seed alone; it's more useful to get the state, which can be done with `random.getstate` anyway. Therefore, I'm closing this issue.
