### ISSUE TITLE
Switch the default behavior of randomization

### ISSUE THREAD

**Issue by windelbouwman** [pytest-dev/pytest-randomly#222]
As the plugin behaves now, tests are randomized when the plugin is installed. I would like to change this behavior, such that when the plugin is installed, an additional option flag (`--randomly-reorganize`) comes available to randomize tests.

The reason for me to want it like this, is that I do not always want to randomize tests, and I would like to explicitly pass an argument when I want to randomize tests.

Another minor reason why this might be better, is that an inverted option (e.g. `--disable-x` or `--no-y`) is arguably slightly more difficult to grasp then it's non-inverted option (e.g. `--enable-x` or `--y`)

Did this topic come up already?

**Comment by adamchainz** [comment]
The 'normal' behaviour for [pytest plugins](https://docs.pytest.org/en/latest/plugins.html) is to be activated on install:

> https://docs.pytest.org/en/latest/plugins.html#deactivating-unregistering-a-plugin-by-nameIf a plugin is installed, pytest automatically finds and integrates it, there is no need to activate it.

You can disable the plugin with `-p no:randomly` : https://docs.pytest.org/en/latest/plugins.html#deactivating-unregistering-a-plugin-by-name

That said if you put that in your config file, you can't override it. Perhaps we could support `--randomly-seed None` to disable it? Would that work?

**Comment by windelbouwman** [comment]
> The 'normal' behaviour for [pytest plugins](https://docs.pytest.org/en/latest/plugins.html) is to be activated on install

Okay, I did not know this, thanks for pointing this out. I would assume that activated means that the plugin is loaded, registered and has it's command line options added, but does not yet change the behavior of how tests are executed.

The problem with this disabling is that you would have to disable each plugin which might be installed. Instead I would like to enable behavior provided by a plugin.

This is however no issue of pytest-randomly, but rather for pytest itself it seems, so feel free to close this issue.

**Comment by adamchainz** [comment]
You are right that it might be a bit counter intuitive that it’s always reorganising.

Can I ask what your use case is that you don’t want to always randomise? I find the benefits come from having them always randomised so interdependence can be discovered quickly.

**Comment by windelbouwman** [comment]
My usecase:

- use pytest to test my code (in a pre-determined order, I think I want the same order each time, but the tests should be interdependent)
- When I suspect some test failing, but I do not know which one, I want to run the tests randomly, so it's likely a failing test is hit early, since tests are grouped by category, it makes sense to randomly jump between categories and have the suite fail fast with the `-x` option.

I hope that makes sense to you. Writing this down, I agree that randomly running tests is actually always a good idea. I think I like the tests being ordered so that the result always produces the same output (in a single word: reproducability).

**Comment by adamchainz** [comment]
Fair enough. Since you think it's a good idea, I'm going to close this issue! Thanks.
