### ISSUE TITLE
Allow to repeat tests.

### ISSUE THREAD

**Issue by tobiasraabe** [pytest-dev/pytest-randomly#228]
Hi everybody,

thanks for developing ``pytest-randomly``! I have a big test suite full of tests working with random data and with changing seeds I feel more confident that I will eventually discover all weird edge cases.

What I would like to propose is to repeat tests with different random seeds derived from the base seed. E.g., I have a test I would like to repeat five times and ``-randomly-seed=5``. Then, the test should be run with seeds 5, 6, 7, 8, 9.

I imagine a solution like

```python
import numpy as np

@pytest.mark.randomly(repetitions=5)
def test():
    arr = np.random.randint(low=0, high=10, size=2)
    assert arr[0] + arr[1] == np.sum(arr)
```

Currently, I interfere in the test generation routine and every test with an argument named ``seed`` is parametrized with increments of ``--randomly-seed``.

**Comment by adamchainz** [comment]
Hi

Thanks for your compliment.

Why do you want this inside the process rather than outside, rerunning the test process a few times? Most users, myself included, rely on the new random seeds being applied over time.

I'm not sure we can add your suggested mark and preserve all behaviour for those seeds in the general case, since we reseed for the module and class levels as well, but afaik we can't repeat those for a new test item generated from a mark. That would mean if e.g. generated seed 6 failed, rerunnning with `--randomly-seed=6` would actually use different seeds for the module and class levels, so it's a different test.

Thanks,

Adam

**Comment by tobiasraabe** [comment]
You are right that I could re-run the test suite five times and have the "same" coverage. In this sense, I would like to have the ability to put more weight on one test case during one test session.

I could also isolate those tests with some custom marker and re-run the test session only for them. Together with your last point, this is probably the easiest way forward.

**Comment by adamchainz** [comment]
There's also [pytest-repeat](https://pypi.org/project/pytest-repeat/) which you can use to mark your tests.

Closing now since you have a resolution.

Thanks,

Adam

**Comment by johannfaouzi** [comment]
I know that this issue has been closed a while ago, but I have not found a solution to my problem which is very related to this issue.

Imagine a code used to simulate the drawing for a tournament. However, not every draw is valid. For instance, teams from the same country or region cannot be drawn in the same group. One ends up with several `if else` loops in the corresponding code. Obviously, for a single draw, only one part of each `if else` loop is ran, so it's not very practical with code coverage. However, with enough runs (**with different random seeds**), one should expect to run each combination at least once. Moreover, if the drawing rules are not complex, it might be possible to derive the theoretical probability that the whole code is covered when running `n` runs (with different random seeds), so one can pick a number of runs such that this probability is greater than a given threshold.

Is there any way of doing this with `pytest` or another package from the ecosystem?

Thanks,
Johann

**Comment by johannfaouzi** [comment]
Never mind, I can just use `random.seed(None)` inside the test function to make each parametrized run use a different random seed.
