### ISSUE TITLE
Provide reverse order

### ISSUE THREAD

**Issue by thbde** [pytest-dev/pytest-randomly#242]
As a developer, I want to execute the tests in reverse order to reveal test dependencies.

Given that the natural order of execution is O={t1, ..., tn}, maybe provide a command line switch that allows to run all tests on reverse order reverse(O)={tn, ..., t1}.

Motivation: 
An empirical study [0] on the test independence assumption (i.e., the result of a test execution does not depend on other test executions) shows, that the reverse strategy can already reveal quite a large amount of test dependencies. A reverse order can reveal more than 70% of all cases for manually created tests and more than 60% of all cases for generated tests, compared to the best detection strategy.

The authors of the study finally suggest to use the randomized strategy. However, the suggestions has limitations in practice. The authors evaluated 10 reruns for random order executions with different seeds. This may lead to a 10x increase in test costs (such as waiting times) and may not be practical. Alternatively to 10 reruns in a row, we could execute the tests in random order only once per commit and observe over time. For each 10 commits, we reach the same threshold of 10 random executions. However, in this case, the commit when a flawed test is introduced may be different to the commit for which the test fails. This leads to higher effort for the root cause detection.

Running the tests in reverse order is a simple and effective approach to detect simple order issues.

(I am also unable to create a PR for this issue because I do not fully understand the logic of the conditionals in the [pytest_collection_modifyitems](https://github.com/pytest-dev/pytest-randomly/blob/f422719d3455be373381253d87654f9e1df4c3e9/src/pytest_randomly.py#L154) function. It would be helpful for a reader to have some comments on why the logic flow is organized in the current way.)

[0] Sai Zhang, Darioush Jalali, Jochen Wuttke, Kıvanç Muşlu, Wing Lam, Michael D. Ernst, and David Notkin. 2014. Empirically revisiting the test independence assumption. In Proceedings of the 2014 International Symposium on Software Testing and Analysis (ISSTA 2014). Association for Computing Machinery, New York, NY, USA, 385–396. doi:https://doi.org/10.1145/2610384.2610404

**Comment by adamchainz** [comment]
Hi @thbde 

Thanks for pointing outt the research!

>  However, in this case, the commit when a flawed test is introduced may be different to the commit for which the test fails. This leads to higher effort for the root cause detection.

Yes it does.

> Running the tests in reverse order is a simple and effective approach to detect simple order issues.

Yes it is. Django's test framework includes a `--reverse` flag for this reason.

You know I would've thought this would exist in pytest core, but it doesn't.

You can make a plugin to allow `--reverse` to reverse the tests with just a few lines:

```python
def pytest_addoption(parser):
    parser._addoption(
        "--reverse",
        action="store",
        ... # todo: fill in remaining arguments
    )


def pytest_collection_modifyitems(session, config, items):
    if config.getoption("reverse"):
        items[:] = items[::-1]
```

Given this is part of Django's test runner, and it's such a small amount of code, it might be suitable for pytest core. Since it's not randomness-based, I don't think it's appropriate here.

I'm interested to see what the pytest core devs say, if you open an issue on pytest core (please tag me, and refer here).

**Comment by thbde** [comment]
I was a bit busy, I will open the issue as suggested. Thank you for your fast feedback.

Regarding your positive reaction to the paper, maybe a short summary and a link to the paper could be a nice addition to the README. This would provide additional arguments and resources to for the interested user of randomly. I can open a PR with some text if you want.

**Comment by adamchainz** [comment]
Yes please, and on pytest-reverse ! It's also worth mentioning pytest-reverse on  https://docs.pytest.org/en/latest/flaky.html

**Comment by thbde** [comment]
I as busy with some other tasks, but here we go. I also added a link to pytest-reverse.

I tried to keep the amount of text low. Please share your thoughts if you prefer more explanation and reasoning like in my initial post here.

Feel free to close this issue after accepting the PR.

**Comment by adamchainz** [comment]
Thank you! 🙏

Good work with the references section.
