### ISSUE TITLE
using PyTorch rng via entry point

### ISSUE THREAD

**Issue by janfb** [pytest-dev/pytest-randomly#249]
Thanks for providing this plugin, looks great! 

I am running tests in a project relying in `PyTorch` and I want to use the corresponding `rng`. I tried to follow your documentation and added 
```
[options.entry_points]
pytest_randomly.random_seeder =
    torch = torch.manual_seed
```
to my `setup.cfg`. 

However, `torch` is not in the name space when reseed function is called in https://github.com/pytest-dev/pytest-randomly/blob/f7e377b351456051ad1e10afb7665155419c239c/src/pytest_randomly.py#L152 

What am I missing? 

Thanks for your help!

**Comment by adamchainz** [comment]
I'm not sure you can write an entry point that refers to another module? You might have to import that function into your own project's module.

**Comment by janfb** [comment]
OK, thanks!

**Comment by adamchainz** [comment]
Did you get it working?

**Comment by donpatrice** [comment]
What worked for me was importing `manual_seed` in the myproject namespace:
```
$ cat myproject/__init__.py

from torch import manual_seed as reseed
```
and then adding `entry_points` in `setup.py`
```
setuptools.setup(
...
    entry_points={
        "pytest_randomly.random_seeder": ["myproject = myproject:reseed"],
    },
...
)
```
