### ISSUE TITLE
crashes with numpy and --randomly-seed=7106521602475165645

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest-randomly#269]
```
 INTERNALERROR>   File "/home/runner/work/pytest-randomly/pytest-randomly/.tox/py36/lib/python3.6/site-packages/pytest_randomly.py", line 144, in _reseed
INTERNALERROR>     np_random.seed(seed)
INTERNALERROR>   File "mtrand.pyx", line 243, in numpy.random.mtrand.RandomState.seed
INTERNALERROR>   File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
INTERNALERROR>   File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
INTERNALERROR> ValueError: Seed must be between 0 and 2**32 - 1
```

looks like some sort of seed truncation is needed:
```python
def _numpy_seed(seed):
    return seed if 0 <= seed <= 2**32-1 else random.Random(seed).getrandbits(32)
```

**Comment by graingert** [comment]
also this is legacy seeding ? https://numpy.org/doc/1.19/reference/random/bit_generators/index.html#seeding-and-entropy
https://numpy.org/doc/1.19/reference/random/generated/numpy.random.RandomState.seed.html#numpy.random.RandomState.seed

not sure what the modern seeding looks like

**Comment by graingert** [comment]
```python
def _to_bytes(x):
    return x.to_bytes(x.bit_length(), "big")

def _from_bytes(x):
    return int.from_bytes(x, "big")

def _sha512(x):
    return hashlib.sha512(x).digest()

def _truncate_seed(seed):
    seed = abs(seed)
    return (
        seed
        if seed <= 2 ** 32 - 1
        else _from_bytes(_sha512(_to_bytes(seed))[:32//8])
    )
```

**Comment by adamchainz** [comment]
That would work, but what's wrong with using modulo? It would ignore some bits but I doubt many people run with seeds using the same right hand 32 bits?

**Comment by adamchainz** [comment]
Or indeed, xoring the 4 byte chunks...

**Comment by graingert** [comment]
modulo and xoring with chunks are just different "hashing/crc" algorithm, and there are other ones with various different properties, eg zlib.adler32, murmur3 etc.

I suggested sha512 because that's what random.Random.seed does: https://github.com/python/cpython/blob/3.8/Lib/random.py#L149-L150

**Comment by tupui** [comment]
@adamchainz I would not advertise seeding NumPy anymore.

The recommended way is to use a random generator which does not use global seeding but the seed is to be passed as an argument when creating the class. For instance in SciPy, we are moving away from the global seeding as much as we can and you would not seed anything by using the global variable. Lot of packages are going along the same road.

**Comment by graingert** [comment]
The recommended way is to always avoid globally seeded random values, pytest-randomly helps detect places that accidentally use them

**Comment by tupui** [comment]
I can see how this could help, but it did not seem like the advertised feature to me. I thought the goal was to seed NumPy for every tests. Not really make some wrong random seeding to detect tests. Some notes about the real intent in the doc might help.

**Comment by adamchainz** [comment]
> @adamchainz I would not advertise seeding NumPy anymore.

Please don't reply on >1 year old threads. Open a new issue if you have an issue.

pytest-randomly has no opinion about how you "should" use numpy. numpy may have such opinions but they do not need repeating here.

pytest-randomly resets numpy's global seed as that might help your tests if you're using numpy's global random generator. You might not even have control over the code that does that.

To clarify a bit, I've added the word "global" in the docs in #405.

**Comment by tupui** [comment]
@adamchainz Sorry on some projects it's fine to comment on old threads (namely SciPy for instance).

It's not really about "opinions", if you advertise fixing NumPy's seed, users might be mislead since the good practice,  used by downstream projects, is to use a generator and not rely on the global seeding. Your change makes it a bit clearer in the doc, thanks!
