### ISSUE TITLE
Make it more clear in the README how to re-order tests

### ISSUE THREAD

**Issue by johnthagen** [pytest-dev/pytest-randomly#303]
I couldn't find it referenced how to use this plugin to reorder tests randomly (vs. affecting the random seed). Does this happen implicitly if the plugin is installed? I think making more explicit that this happens would be a nice addition to the docs.

**Comment by johnthagen** [comment]
Reading it again, I see:

> All of these features are on by default but can be disabled with flags.

I think this is clear enough on a second pass. For some reason I was expecting a switch.

**Comment by adamchainz** [comment]
Thanks for coming back and closing. I'd also point out many pytest plugins implicitly add features if they're installed, so it's somewhat idiomatic.
