### ISSUE TITLE
Dependency resolution issue with Poetry

### ISSUE THREAD

**Issue by pawamoy** [pytest-dev/pytest-randomly#335]
Just so you know, `backports.entry-points-selectable` specifies Python markers for its `pytest-mypy` dependency that are not being parsed correctly by Poetry, resulting in errors while resolving dependencies for pytest-randomly 3.6.0. See https://github.com/python-poetry/poetry/issues/3862#issuecomment-812490791 and the previous comments. I'll temporarily pin pytest-randomly to 3.5.0 :slightly_smiling_face:

**Comment by adamchainz** [comment]
I suggest you also open an issue upstream in `backports.entry-points-selectable`. That's only a testing requirement so I don't see why poetry would even need to touch it if you didn't specify to install `backports.entry-points-selectable[testing]`

**Comment by pawamoy** [comment]
Yes I already did yesterday: https://github.com/jaraco/backports.entry_points_selectable/issues/2 :slightly_smiling_face:  

As for why Poetry reads these, I'm not knowledgeable enough in dependency resolution algorithms or Poetry itself to answer! :smile:

**Comment by hukkinj1** [comment]
I went ahead and opened a [PR](https://github.com/jaraco/backports.entry_points_selectable/pull/3) for this before realizing this closed issue existed.

I think specifying the dependencies as `>= 3` makes more sense even if the Poetry issue is fixed. As far as I know `>3` is equivalent to `>=3 and !=3`. Feels a bit strange to me to arbitrarily exclude Python version 3.0.0 (but not 3.0.1 for instance).
