### ISSUE TITLE
Breaks on python3.10

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest-randomly#349]
Cannot import importlib_metadata.

**Comment by adamchainz** [comment]
I know #341.

**Comment by gaborbernat** [comment]
That issue is closed, but the problem still persists.

**Comment by adamchainz** [comment]
You're coming across quite entitled. I will get around to Python 3.10 support when I get around to it.

**Comment by gaborbernat** [comment]
I wasn't demanding, just saying you shouldn't close the issue until you actually fix the issue.

**Comment by adamchainz** [comment]
I upgrade all my open source projects on a schedule, with a script. I cannot keep track of individual project issues.

**Comment by gaborbernat** [comment]
Perhaps then leave the issue open and let the person opening the issue close it once they confirm it's done?

**Comment by adamchainz** [comment]
Version 3.8.0 is now available with Python 3.10 support.

**Comment by gaborbernat** [comment]
Thanks a lot! 🙇
