### ISSUE TITLE
sdist is missing tests

### ISSUE THREAD

**Issue by mtelka** [pytest-dev/pytest-randomly#526]
### Python Version

NA

### pytest Version

NA

### Package Version

3.12.0

### Description

The sdist at PyPI is missing tests.  Please add tests to sdist to make downstream testing easier.  Thank you.

**Comment by adamchainz** [comment]
See https://github.com/pytest-dev/pytest-randomly/pull/519#issuecomment-1399219955 . If you have anything to add to that conversation, please continue it here.

And please search the issue tracker for relevant discussions before filing issues.

**Comment by mtelka** [comment]
I'm sorry to see this closed since tests included in the source distribution would allow easy automatic testing of `pytest-randomly` during packaging this project for [OpenIndiana](https://www.openindiana.org/).  Without tests included, we would either not running tests for the `pytest-randomly` package at all, or we need to do some manual work with every `pytest-randomly` upgrade to make sure tests are downloaded from github.

Please note that PyPI does not point to github tarballs.  It points to sdists hosted at PyPI.  So we cannot simply ask PyPI to get url for tar.gz at github and there seems to be no reliable way how to construct one.

Anyway, this is your project and your decision, so we need to adapt.

**Comment by adamchainz** [comment]
> Without tests included, we would either not running tests for the `pytest-randomly` package at all, or we need to do some manual work with every `pytest-randomly` upgrade to make sure tests are downloaded from github.

My experience with repackaging attempts is that the test suite is run under different conditions (i.e. not under the `tox` setup in this repo), leading mostly to false positive failures.

I would advise just not runnign tests - the project is pure Python, so unlikely to fail in any interesting way based on packaging, and any bugs need reporting here anyway.

> So we cannot simply ask PyPI to get url for tar.gz at github and there seems to be no reliable way how to construct one.

FYI you can see the URL's on https://github.com/pytest-dev/pytest-randomly/tags - simply inject version number...

**Comment by mtelka** [comment]
Thank you for your time.  I really appreciate.

FYI, here is detailed explanation why github tarballs cause (minor) inconvenience for us: https://github.com/encukou/py3c/issues/56#issuecomment-1446593685

**Comment by adamchainz** [comment]
You wrote:

> This works well, and it is only a minor burden in our tooling, but it could be a problem once the above url no longer works (for example if you switch from github to ..., or move the project from encukou to ..., etc.). In that case we would need to update our config manually, which we would like to avoid, if possible.

IMO if you're repackaging a project, it's your responsibility to keep your config up to date. Projects shouldn't need to worry about their tooling to match your repackaging needs.

(And honestly, why even repackage pytest-randomly etc.? It's for Python developers, who shoudl be able to run `pip install`...)

**Comment by martin-kokos** [comment]
It would be courteous to allow the post-install process to run tests to verify correct behavior and not hope for the best as pip does normally, although it *did* have a ` pip install --install-option test ...` feature to do just that.
