### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest-randomly#565]
### Description

Is it possible next time on release new version make the github release to have entry on hhttps://github.com/pytest-dev/pytest-randomly/releases entries? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by adamchainz** [comment]
No, for the same reason given in https://github.com/adamchainz/time-machine/issues/378 . There’s an existing notification system on PyPI, use that.

I see on your profile that you spammed this request to many projects:

<img width="808" alt="Xnapper-2023-09-22-10 48 34" src="https://github.com/pytest-dev/pytest-randomly/assets/857609/d05999f7-23b4-4c12-be46-4e25b1dc3a52">

I think it’s not great behaviour to spam many maintainers with a request for extra work with only a small benefit.
