### ISSUE TITLE
Integration with pytest-rerunfailures

### ISSUE THREAD

**Issue by danmash** [pytest-dev/pytest-randomly#631]
### Description

Hi, thank you for working on the plugin! I would like to request integration with the pytest-rerunfailures plugin, which would allow me to rerun failed tests without using an additional `pytest` call. The current problem is that when I use pytest-randomly and pytest-rerunfailures together, the rerunfailures use the same random seed again and again.
The other plugin's maintainers don't want to take this responsibility. 
https://github.com/pytest-dev/pytest-rerunfailures/issues/125
Could you please check if it's possible to make the change on your side? 

Thank you,
Regards

**Comment by adamchainz** [comment]
What you're asking is also counter to this package... The point of pytest-randomly is to use the same seed during the test run, for reproducibility. Rolling through extra seeds when a test reruns seems like something that could hurt as much as fix things.

If you need something custom, extend the fixtures in your project.
