### ISSUE TITLE
Consider moving to the pytest-dev organization

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-randomly#94]
Hi!

Just stumbled on this plugin! It looks like a much better version (and maintained!) of the honorable https://github.com/klrmn/pytest-random.

Would you like to consider moving it under the `pytest-dev` organization for more visibility? You can read more about this [here](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#submitting-plugins-to-pytest-dev). 👍

**Comment by adamchainz** [comment]
Yo, I did add an item on my todo list ages to suggest this, but it fell down the priority list. I'm happy to move it over as long as I don't have to change much about the process here - I maintain all my ~30 OSS packages in basically the same layout and update them together to keep consistent.

**Comment by adamchainz** [comment]
n.b. i also have https://github.com/adamchainz/pytest-restrict , https://github.com/adamchainz/pytest-super-check , and https://github.com/adamchainz/pytest-flake8dir , but they're more niche

**Comment by nicoddemus** [comment]
> I'm happy to move it over as long as I don't have to change much about the process here

The idea of moving plugins over to the pytest-dev organization is two-fold:

* Avoid plugin abandon; by moving to the org, other people have write access to the repository and PyPI publish rights so in case if ever the original author (you in this case) become **unresponsive** to issues/releases/PRs others can take over. As an example, [pytest-capturelog](https://bitbucket.org/memedough/pytest-capturelog/overview) where the author has stopped making releases (last one was 2010), has not being responding to issues or attempts for contact. Since then that plugin has forked into [pytest-catchlog](https://github.com/eisensheng/pytest-catchlog) and merged into the core, but if `pytest-capturelog` were under the `pytest-dev` organization, other people would be able at least to change the `README` to indicate that the plugin is deprecated.
* Give more visibility to the plugin; with over 300 plugins now, it is far to separate those which are well maintained from those which were just an experiment or have been abandoned.

The plugin for all effects would be still under your full control (access, publishing, adding more collaborators, etc), it would just be under `pytest-dev` insted of `adamchainz`. I see you met our minimum standards (having CI, LICENSE, etc) so I don't see any problems or changes to your process that would be required. 😄

**Comment by adamchainz** [comment]
Ok cool, let's do it. IRC me on @adamchainz to sync?

**Comment by nicoddemus** [comment]
The protocol is to submit an email to the mailing list:

> You can submit your plugin by subscribing to the pytest-dev mail list and writing a mail pointing to your existing pytest plugin repository which must have the following...

We can go from there. 👍

**Comment by adamchainz** [comment]
Ok wilco

**Comment by adamchainz** [comment]
done
